/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationTanstackQueryRouteImport } from './routes/integration/tanstack-query'
import { Route as IntegrationTableRouteImport } from './routes/integration/table'
import { Route as IntegrationStoreRouteImport } from './routes/integration/store'
import { Route as IntegrationDrizzleRouteImport } from './routes/integration/drizzle'
import { Route as DemoTodoRouteImport } from './routes/demo/todo'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as ApiTodoRouteImport } from './routes/api/todo'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as IntegrationBetterAuthIndexRouteImport } from './routes/integration/better-auth/index'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as UiActionButtonRouteImport } from './routes/ui/action/button'
import { Route as IntegrationTanstackDbChatApiRouteImport } from './routes/integration/tanstack-db/chat-api'
import { Route as IntegrationTanstackDbChatRouteImport } from './routes/integration/tanstack-db/chat'
import { Route as IntegrationOrpcTodoRouteImport } from './routes/integration/orpc/todo'
import { Route as IntegrationI18nParaglideRouteImport } from './routes/integration/i18n/paraglide'
import { Route as IntegrationFormSimpleRouteImport } from './routes/integration/form/simple'
import { Route as IntegrationFormAddressRouteImport } from './routes/integration/form/address'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationTanstackQueryRoute =
  IntegrationTanstackQueryRouteImport.update({
    id: '/integration/tanstack-query',
    path: '/integration/tanstack-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationTableRoute = IntegrationTableRouteImport.update({
  id: '/integration/table',
  path: '/integration/table',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationStoreRoute = IntegrationStoreRouteImport.update({
  id: '/integration/store',
  path: '/integration/store',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationDrizzleRoute = IntegrationDrizzleRouteImport.update({
  id: '/integration/drizzle',
  path: '/integration/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTodoRoute = DemoTodoRouteImport.update({
  id: '/demo/todo',
  path: '/demo/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/demo/ai-chat',
  path: '/demo/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodoRoute = ApiTodoRouteImport.update({
  id: '/api/todo',
  path: '/api/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationBetterAuthIndexRoute =
  IntegrationBetterAuthIndexRouteImport.update({
    id: '/integration/better-auth/',
    path: '/integration/better-auth/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/demo/guitars/',
  path: '/demo/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiActionButtonRoute = UiActionButtonRouteImport.update({
  id: '/ui/action/button',
  path: '/ui/action/button',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationTanstackDbChatApiRoute =
  IntegrationTanstackDbChatApiRouteImport.update({
    id: '/integration/tanstack-db/chat-api',
    path: '/integration/tanstack-db/chat-api',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationTanstackDbChatRoute =
  IntegrationTanstackDbChatRouteImport.update({
    id: '/integration/tanstack-db/chat',
    path: '/integration/tanstack-db/chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationOrpcTodoRoute = IntegrationOrpcTodoRouteImport.update({
  id: '/integration/orpc/todo',
  path: '/integration/orpc/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationI18nParaglideRoute =
  IntegrationI18nParaglideRouteImport.update({
    id: '/integration/i18n/paraglide',
    path: '/integration/i18n/paraglide',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationFormSimpleRoute = IntegrationFormSimpleRouteImport.update({
  id: '/integration/form/simple',
  path: '/integration/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationFormAddressRoute = IntegrationFormAddressRouteImport.update({
  id: '/integration/form/address',
  path: '/integration/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/demo/guitars/$guitarId',
  path: '/demo/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/demo/api/ai/chat',
  path: '/demo/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/todo': typeof ApiTodoRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/todo': typeof DemoTodoRoute
  '/integration/drizzle': typeof IntegrationDrizzleRoute
  '/integration/store': typeof IntegrationStoreRoute
  '/integration/table': typeof IntegrationTableRoute
  '/integration/tanstack-query': typeof IntegrationTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/integration/form/address': typeof IntegrationFormAddressRoute
  '/integration/form/simple': typeof IntegrationFormSimpleRoute
  '/integration/i18n/paraglide': typeof IntegrationI18nParaglideRoute
  '/integration/orpc/todo': typeof IntegrationOrpcTodoRoute
  '/integration/tanstack-db/chat': typeof IntegrationTanstackDbChatRoute
  '/integration/tanstack-db/chat-api': typeof IntegrationTanstackDbChatApiRoute
  '/ui/action/button': typeof UiActionButtonRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/integration/better-auth/': typeof IntegrationBetterAuthIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/todo': typeof ApiTodoRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/todo': typeof DemoTodoRoute
  '/integration/drizzle': typeof IntegrationDrizzleRoute
  '/integration/store': typeof IntegrationStoreRoute
  '/integration/table': typeof IntegrationTableRoute
  '/integration/tanstack-query': typeof IntegrationTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/integration/form/address': typeof IntegrationFormAddressRoute
  '/integration/form/simple': typeof IntegrationFormSimpleRoute
  '/integration/i18n/paraglide': typeof IntegrationI18nParaglideRoute
  '/integration/orpc/todo': typeof IntegrationOrpcTodoRoute
  '/integration/tanstack-db/chat': typeof IntegrationTanstackDbChatRoute
  '/integration/tanstack-db/chat-api': typeof IntegrationTanstackDbChatApiRoute
  '/ui/action/button': typeof UiActionButtonRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/integration/better-auth': typeof IntegrationBetterAuthIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/todo': typeof ApiTodoRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/todo': typeof DemoTodoRoute
  '/integration/drizzle': typeof IntegrationDrizzleRoute
  '/integration/store': typeof IntegrationStoreRoute
  '/integration/table': typeof IntegrationTableRoute
  '/integration/tanstack-query': typeof IntegrationTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/integration/form/address': typeof IntegrationFormAddressRoute
  '/integration/form/simple': typeof IntegrationFormSimpleRoute
  '/integration/i18n/paraglide': typeof IntegrationI18nParaglideRoute
  '/integration/orpc/todo': typeof IntegrationOrpcTodoRoute
  '/integration/tanstack-db/chat': typeof IntegrationTanstackDbChatRoute
  '/integration/tanstack-db/chat-api': typeof IntegrationTanstackDbChatApiRoute
  '/ui/action/button': typeof UiActionButtonRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/integration/better-auth/': typeof IntegrationBetterAuthIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mcp'
    | '/api/$'
    | '/api/todo'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/mcp-todos'
    | '/demo/todo'
    | '/integration/drizzle'
    | '/integration/store'
    | '/integration/table'
    | '/integration/tanstack-query'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/demo/api/mcp-todos'
    | '/demo/guitars/$guitarId'
    | '/integration/form/address'
    | '/integration/form/simple'
    | '/integration/i18n/paraglide'
    | '/integration/orpc/todo'
    | '/integration/tanstack-db/chat'
    | '/integration/tanstack-db/chat-api'
    | '/ui/action/button'
    | '/demo/guitars/'
    | '/integration/better-auth/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mcp'
    | '/api/$'
    | '/api/todo'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/mcp-todos'
    | '/demo/todo'
    | '/integration/drizzle'
    | '/integration/store'
    | '/integration/table'
    | '/integration/tanstack-query'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/demo/api/mcp-todos'
    | '/demo/guitars/$guitarId'
    | '/integration/form/address'
    | '/integration/form/simple'
    | '/integration/i18n/paraglide'
    | '/integration/orpc/todo'
    | '/integration/tanstack-db/chat'
    | '/integration/tanstack-db/chat-api'
    | '/ui/action/button'
    | '/demo/guitars'
    | '/integration/better-auth'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/mcp'
    | '/api/$'
    | '/api/todo'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/mcp-todos'
    | '/demo/todo'
    | '/integration/drizzle'
    | '/integration/store'
    | '/integration/table'
    | '/integration/tanstack-query'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/demo/api/mcp-todos'
    | '/demo/guitars/$guitarId'
    | '/integration/form/address'
    | '/integration/form/simple'
    | '/integration/i18n/paraglide'
    | '/integration/orpc/todo'
    | '/integration/tanstack-db/chat'
    | '/integration/tanstack-db/chat-api'
    | '/ui/action/button'
    | '/demo/guitars/'
    | '/integration/better-auth/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  McpRoute: typeof McpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiTodoRoute: typeof ApiTodoRoute
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoTodoRoute: typeof DemoTodoRoute
  IntegrationDrizzleRoute: typeof IntegrationDrizzleRoute
  IntegrationStoreRoute: typeof IntegrationStoreRoute
  IntegrationTableRoute: typeof IntegrationTableRoute
  IntegrationTanstackQueryRoute: typeof IntegrationTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  IntegrationFormAddressRoute: typeof IntegrationFormAddressRoute
  IntegrationFormSimpleRoute: typeof IntegrationFormSimpleRoute
  IntegrationI18nParaglideRoute: typeof IntegrationI18nParaglideRoute
  IntegrationOrpcTodoRoute: typeof IntegrationOrpcTodoRoute
  IntegrationTanstackDbChatRoute: typeof IntegrationTanstackDbChatRoute
  IntegrationTanstackDbChatApiRoute: typeof IntegrationTanstackDbChatApiRoute
  UiActionButtonRoute: typeof UiActionButtonRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  IntegrationBetterAuthIndexRoute: typeof IntegrationBetterAuthIndexRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-query': {
      id: '/integration/tanstack-query'
      path: '/integration/tanstack-query'
      fullPath: '/integration/tanstack-query'
      preLoaderRoute: typeof IntegrationTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/table': {
      id: '/integration/table'
      path: '/integration/table'
      fullPath: '/integration/table'
      preLoaderRoute: typeof IntegrationTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/store': {
      id: '/integration/store'
      path: '/integration/store'
      fullPath: '/integration/store'
      preLoaderRoute: typeof IntegrationStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/drizzle': {
      id: '/integration/drizzle'
      path: '/integration/drizzle'
      fullPath: '/integration/drizzle'
      preLoaderRoute: typeof IntegrationDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/todo': {
      id: '/demo/todo'
      path: '/demo/todo'
      fullPath: '/demo/todo'
      preLoaderRoute: typeof DemoTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/demo/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todo': {
      id: '/api/todo'
      path: '/api/todo'
      fullPath: '/api/todo'
      preLoaderRoute: typeof ApiTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/better-auth/': {
      id: '/integration/better-auth/'
      path: '/integration/better-auth'
      fullPath: '/integration/better-auth/'
      preLoaderRoute: typeof IntegrationBetterAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/demo/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/action/button': {
      id: '/ui/action/button'
      path: '/ui/action/button'
      fullPath: '/ui/action/button'
      preLoaderRoute: typeof UiActionButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-db/chat-api': {
      id: '/integration/tanstack-db/chat-api'
      path: '/integration/tanstack-db/chat-api'
      fullPath: '/integration/tanstack-db/chat-api'
      preLoaderRoute: typeof IntegrationTanstackDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/tanstack-db/chat': {
      id: '/integration/tanstack-db/chat'
      path: '/integration/tanstack-db/chat'
      fullPath: '/integration/tanstack-db/chat'
      preLoaderRoute: typeof IntegrationTanstackDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/orpc/todo': {
      id: '/integration/orpc/todo'
      path: '/integration/orpc/todo'
      fullPath: '/integration/orpc/todo'
      preLoaderRoute: typeof IntegrationOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/i18n/paraglide': {
      id: '/integration/i18n/paraglide'
      path: '/integration/i18n/paraglide'
      fullPath: '/integration/i18n/paraglide'
      preLoaderRoute: typeof IntegrationI18nParaglideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/form/simple': {
      id: '/integration/form/simple'
      path: '/integration/form/simple'
      fullPath: '/integration/form/simple'
      preLoaderRoute: typeof IntegrationFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/form/address': {
      id: '/integration/form/address'
      path: '/integration/form/address'
      fullPath: '/integration/form/address'
      preLoaderRoute: typeof IntegrationFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/demo/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/demo/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  McpRoute: McpRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiTodoRoute: ApiTodoRoute,
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoTodoRoute: DemoTodoRoute,
  IntegrationDrizzleRoute: IntegrationDrizzleRoute,
  IntegrationStoreRoute: IntegrationStoreRoute,
  IntegrationTableRoute: IntegrationTableRoute,
  IntegrationTanstackQueryRoute: IntegrationTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  IntegrationFormAddressRoute: IntegrationFormAddressRoute,
  IntegrationFormSimpleRoute: IntegrationFormSimpleRoute,
  IntegrationI18nParaglideRoute: IntegrationI18nParaglideRoute,
  IntegrationOrpcTodoRoute: IntegrationOrpcTodoRoute,
  IntegrationTanstackDbChatRoute: IntegrationTanstackDbChatRoute,
  IntegrationTanstackDbChatApiRoute: IntegrationTanstackDbChatApiRoute,
  UiActionButtonRoute: UiActionButtonRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  IntegrationBetterAuthIndexRoute: IntegrationBetterAuthIndexRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
